### ISSUE TITLE
When can we get to download and use this ROM?

### ISSUE THREAD

**Issue by sarvesvara** [nian0114/android_kernel_xiaomi_leo#2]
When can we get to download and use this ROM?

**Comment by nian0114** [comment]
http://forum.xda-developers.com/mi-note-pro

**Comment by sarvesvara** [comment]
Thanks for the link.
However, the latest ROM there is around mid of March'16 (Mokee, CM).
I could see your good work coming in Flyme OS. Hope so, the bugs would be fixed soon.
Keep up the good work.
Thanks.

**Comment by sarvesvara** [comment]
We have super matest 6.0.1
